spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/blissfish/blissed-config.git
          force-pull: true
          basedir: C:/data/tmp

management:
  security:
    enabled: false

endpoints:
  sensitive: false

server:
  port: 8888
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/