spring:
  h2:
    console:
        enabled: true  
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
  application:
    name: user-service

management:
  security:
    enabled: false

endpoints:
  sensitive: false

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/